### ISSUE TITLE
Sidecar stopped submitting stats abruptly

### ISSUE THREAD

**Issue by varun-krishna** [lightstep/opentelemetry-prometheus-sidecar#109]
Hello @jmacd 

We have a stackdriver-prometheus-sidecar working on our RKE cluster along with Prometheus containers . Prometheus continued collecting data without issues. However, the sidecar stopped submitting data to StackDriver abruptly . We can manually query the data from Prometheus without issues, there's no missing data.

I have also raised an issue on stackdriver-prometheus-sidecar - https://github.com/Stackdriver/stackdriver-prometheus-sidecar/issues/272

While exploring i found out that you have might well aware of the issue and also fixed the potential problem in one of your contributions to opentelemtry-proemtheus-sidecar.

I would love to use opentelemetry-prometheus-sidecar in our setup if this could solve the issue.

Have some questions -  These are some of the arguments i am using for my  stackdriver-prometheus-sidecar installation 
**_--stackdriver.project-id , stackdriver.kubernetes.location , stackdriver.kubernetes.cluster-name_**   . Can you please let me know what options do i use correspondingly for opentelemetry-prometheus-sidecar deployment so that i can ship metrics to my stack-driver project .

@jmacd any insights here would be really helpfull. awaiting your response 

Logs from stackdriver-prometheus-sidecar 

> 
> level=debug ts=2021-02-08T19:27:42.852Z caller=queue_manager.go:317 component=queue_manager msg=QueueManager.updateShardsLoop lowerBound=0.7 desiredShards=0.001727148154056503 upperBound=1.1
> level=debug ts=2021-02-08T19:27:57.851Z caller=queue_manager.go:306 component=queue_manager msg=QueueManager.calculateDesiredShards samplesIn=6.218261691304947e-68 samplesOut=6.218261691304947e-68 samplesOutDuration=3.435572350977865e-61 timePerSample=5.524972285714282e+06 sizeRate=7261.878464457889 offsetRate=2.684309866779702e-63 desiredShards=0.001394140958393718
> level=debug ts=2021-02-08T19:27:57.851Z caller=queue_manager.go:317 component=queue_manager msg=QueueManager.updateShardsLoop lowerBound=0.7 desiredShards=0.001394140958393718 upperBound=1.1
> level=debug ts=2021-02-08T19:28:12.851Z caller=queue_manager.go:306 component=queue_manager msg=QueueManager.calculateDesiredShards samplesIn=4.974609353043958e-68 samplesOut=4.974609353043958e-68 samplesOutDuration=2.7484578807822917e-61 timePerSample=5.524972285714282e+06 sizeRate=7772.382771566311 offsetRate=2.1474478934237618e-63 desiredShards=0.001492147964082347
> level=debug ts=2021-02-08T19:28:12.851Z caller=queue_manager.go:317 component=queue_manager msg=QueueManager.updateShardsLoop lowerBound=0.7 desiredShards=0.001492147964082347 upperBound=1.1

**Comment by jmacd** [comment]
Interesting! We are tracking a couple of potential theories that might explain this. There is one known problem, the reason why we added https://github.com/lightstep/opentelemetry-prometheus-sidecar/pull/100, related to timeouts in the /api/v1/targets endpoint of the Prometheus server.

Would you look at the logs of the Prometheus server, from around when the sidecar goes dead, and see if you see Broken Pipe messages coming from the web api?

**Comment by varun-krishna** [comment]
@jmacd  , Thanks for the response. Please find below the  logs from Prometheus. 

prometheus logs 

> level=info ts=2021-02-09T05:02:33.979Z caller=main.go:302 msg="No time or size retention was set so using the default time retention" duration=15d
> level=info ts=2021-02-09T05:02:33.980Z caller=main.go:337 msg="Starting Prometheus" version="(version=2.19.2, branch=HEAD, revision=c448ada63d83002e9c1d2c9f84e09f55a61f0ff7)"
> level=info ts=2021-02-09T05:02:33.980Z caller=main.go:338 build_context="(go=go1.14.4, user=root@dd72efe1549d, date=20200626-09:02:20)"
> level=info ts=2021-02-09T05:02:33.980Z caller=main.go:339 host_details="(Linux 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020 x86_64 prometheus-deployment-56f966686b-w89rp (none))"
> level=info ts=2021-02-09T05:02:33.980Z caller=main.go:340 fd_limits="(soft=1048576, hard=1048576)"
> level=info ts=2021-02-09T05:02:33.980Z caller=main.go:341 vm_limits="(soft=unlimited, hard=unlimited)"
> level=info ts=2021-02-09T05:02:33.983Z caller=main.go:678 msg="Starting TSDB ..."
> level=info ts=2021-02-09T05:02:33.983Z caller=web.go:524 component=web msg="Start listening for connections" address=0.0.0.0:9090
> level=info ts=2021-02-09T05:02:33.999Z caller=head.go:645 component=tsdb msg="Replaying WAL and on-disk memory mappable chunks if any, this may take a while"
> level=info ts=2021-02-09T05:02:34.001Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=0 maxSegment=0
> level=info ts=2021-02-09T05:02:34.001Z caller=head.go:709 component=tsdb msg="WAL replay completed" duration=1.888906ms
> level=info ts=2021-02-09T05:02:34.004Z caller=main.go:694 fs_type=EXT4_SUPER_MAGIC
> level=info ts=2021-02-09T05:02:34.004Z caller=main.go:695 msg="TSDB started"
> level=info ts=2021-02-09T05:02:34.004Z caller=main.go:799 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
> level=info ts=2021-02-09T05:02:34.007Z caller=kubernetes.go:253 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
> level=info ts=2021-02-09T05:02:34.010Z caller=kubernetes.go:253 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
> level=info ts=2021-02-09T05:02:34.012Z caller=kubernetes.go:253 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
> level=info ts=2021-02-09T05:02:34.014Z caller=main.go:827 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml
> level=info ts=2021-02-09T05:02:34.014Z caller=main.go:646 msg="Server is ready to receive web requests."

Also would like to use the opentelemetry-prometheus-sidecar , can you please guide on the corresponding options to use for  the arguments **--stackdriver.project-id , stackdriver.kubernetes.location , stackdriver.kubernetes.cluster-name**   for deploying  opentelemetry-prometheus-sidecar ?
