### ISSUE TITLE
Rename flag --opentelemetry.api-address to --opentelemetry.endpoint?

### ISSUE THREAD

**Issue by jmacd** [lightstep/opentelemetry-prometheus-sidecar#24]
This question came up during an internal review of the README.

**Comment by jmacd** [comment]
@codeboten what flag name do you like? Maybe `--opentelemetry.endpoint` (for consistency w/ other flags)?

**Comment by codeboten** [comment]
i think `--opentelemetry.endpoint` makes sense and aligns with terminology here https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/protocol/exporter.md

**Comment by jmacd** [comment]
Closed by #25.
